chicago = Location.create({
  city: 'Chicago',
  state: 'IL',
  country: 'USA',
  })

User.create([
  {
    email_address: 'rossgellere@email.com',
    password: 'password',
    first_name: 'Ross',
    last_name: 'Geller',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/David_Schwimmer_as_Ross_Geller.jpg/220px-David_Schwimmer_as_Ross_Geller.jpg',
    job_title: 'Paleontologist',
    expertiseArray: 'flirtatious, smart, caring, understanding',
    bio: 'While he is smart, polite, caring, thoughtful and kind, Ross is often clumsy and socially awkward - taking the characteristics of the stereotypical "loser nerd". He is sometimes shown to have a good sense of humor. He is the only member of the group of friends with a doctorate and, as such, can be arrogant.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'minervamcgonagall@email.com',
    password: 'password',
    first_name: 'Minerva',
    last_name: 'McGonagall',
    profile_pic: 'https://pixel.nymag.com/imgs/daily/vulture/2018/09/06/06-minerva-mcgonagall.w700.h700.jpg',
    job_title: 'Professor',
    expertiseArray: 'transfiguration,animagus,duelling,charms',
    bio: 'I am the Head of Gryffindor House, and a Transfiguration professor.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'jackbauer@gmail.com',
    password: 'password',
    first_name: 'Jack',
    last_name: 'Bauer',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Jack_Bauer.jpg/220px-Jack_Bauer.jpg',
    job_title: 'Agent',
    expertiseArray: 'badass, dedication, stealth, persuasion, interrogation',
    bio: 'Jack Bauer is a retired American serviceman and a former federal agent, who was responsible for saving numerous American citizens from potentially devastating terrorist attacks on more than one occasion.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'leslieknope@gmail.com',
    password: 'password',
    first_name: 'Leslie',
    last_name: 'Knope',
    profile_pic: "https://s.yimg.com/ny/api/res/1.2/OtlQfH0YnwCyBf5_TnjP1g--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9NzQ0O2g9NDE5/http://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/a452a2dde1655c64ad4c5edfbd5ebc2d",
    job_title: 'Deputy Director',
    expertiseArray: 'trustworthy, conflict-resolution, leadership, humor, advocacy, ',
    bio: 'Leslie is a mid-level bureaucrat in the Parks and Recreation Department of Pawnee, Indiana who hopes to advance her career and improve her town, while working towards her goal of becoming the first female President.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'gregoryhouse@gmail.com',
    password: 'password',
    first_name: 'Gregory',
    last_name: 'House',
    profile_pic: 'https://vignette.wikia.nocookie.net/house/images/e/ef/House-karakter.jpg/revision/latest/scale-to-width-down/340?cb=20100909011921&path-prefix=tr',
    job_title: 'Doctor',
    expertiseArray: 'genius, genuine',
    bio: 'Gregory House is a misanthropic medical genius who heads a team of diagnosticians at the Princeton-Plainsboro Teaching Hospital in New Jersey. He is widely renown for his skills. People from all over the world come to meet him for diagnosis. The government hires him at times as well.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'georgecostanza@gmail.com',
    password: 'password',
    first_name: 'George',
    last_name: 'Costanza',
    profile_pic: 'https://vignette.wikia.nocookie.net/seinfeld/images/7/76/George-costanza.jpg/revision/latest?cb=20110406222711',
    job_title: 'Real Estate Agent',
    expertiseArray: 'neurotic, self-loating, loveable, insecure',
    bio: 'Not much to say',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'dondraper@gmail.com',
    password: 'password',
    first_name: 'Don',
    last_name: 'Draper',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Don_Draper_Wiki.jpg',
    job_title: 'Creative Director',
    expertiseArray: 'Advertising, sales, adaptability, writing, creativity',
    bio: 'Don" Draper is a founding partner and the Creative Director at Sterling Cooper Draper Pryce Advertising Agency in Manhattan, NY ("Shut the Door. Have a Seat"). Prior to that position, he was the Director of the Creative Department at the Sterling Cooper Advertising Agency.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'tonysoprano@gmail.com',
    password: 'password',
    first_name: 'Tony',
    last_name: 'Soprano',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Tony_Soprano.jpg/270px-Tony_Soprano.jpg',
    job_title: 'Crime Boss',
    expertiseArray: 'Violent, caring, protective, repulsive, intelligent, loving',
    bio: 'The De facto Boss of the DiMeo crime family.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
 
  {
    email_address: 'michaelscott@gmail.com',
    password: 'password',
    first_name: 'Michael',
    last_name: 'Scott',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
    job_title: 'Branch Manager',
    expertiseArray: 'immature, extroverted, enthusiastic, self-centered, impetuous',
    bio: 'Former branch manager of the Scranton branch of Dunder Mifflin Paper Company, The Michael Scott Paper Company, and later Dunder Mifflin Sabre.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'walterwhite@gmail.com',
    password: 'password',
    first_name: 'Walter',
    last_name: 'White',
    profile_pic: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/65/Walter_White2.jpg/220px-Walter_White2.jpg',
    job_title: 'Teacher',
    expertiseArray: 'controlling, intelligent, family-man, guts, patience, perfection, instincts, adaptive',
    bio: 'Walter White is a high school chemistry teacher and family man.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
])